### ISSUE TITLE
Container::buildObject may result in infitite loop

### ISSUE THREAD

**Issue by piotr-cz** [joomla-framework/di#4] opened 2014-04-10 07:41 UTC
The `buildObject` method [uses](https://github.com/joomla-framework/di/blob/master/src/Container.php#L142) `set` method at the bottom.

In specific case this may lead to infinite loop of
`Joomla\DI\Container->buildObject()` and `Joomla\DI\Container->getMethodArgs()` methods resulting in 
`Fatal error: Maximum function nesting level of '100' reached, aborting!`

Because same key is being set in two places at a time:

``` PHP
$fqcn = '\\Extension\\vendor\\FooComponent\\FooComponent';
$data = array();

$container->set(
    $fqcn,
    function (Container $c) use ($fqcn, $data)
    {
        $instance = $c->buildObject($fqcn);
        $instance->setData($data);

        return $instance;
    }
);
```

I'm not sure if this is a bug (I'd say the `set` method shouldn't be part of the `buildObject`) or I misunderstood the functionality.

**Comment by nibra** [comment] 2015-08-06 18:43
The problem is not caused by the call to `set()`, but by a circular dependency. `$fqcn` has to be resolved in order to resolve `$fqcn`, which leads to an endless loop.

There's no way to get around this; however, `buildObject()` can be changed to detect that and throw an exception. I solved that already in my repo, PR comes when I'm done with the documentation.

**Comment by mbabker** [comment] 2018-02-25 16:35
Fixed via https://github.com/joomla-framework/di/commit/33c66e4091e4433f33ddf4a0ac36604cf3b73c41 for 1.x (by backporting appropriate changes from #16).

**Closed by mbabker** 2018-02-25 16:35 UTC
